name: Release snap
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'upload artifact'
        required: true
        default: 'yes'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      UPLOAD_ARTIFACT: ${{ github.event.inputs.upload_artifact }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      DEBUG: ${{ true }}
    steps:
      - name: Checkout release
        uses: actions/checkout@v2
      - name: Check environment variables
        if : ${{ env.DEBUG }}
        run: |
          echo $PWD
          echo "upload artifact: ($UPLOAD_ARTIFACT)"
          echo "release tag: ($RELEASE_TAG)"
          echo "deubg: ($DEBUG)"
          echo "release tag empty: (${{ env.RELEASE_TAG == '' }})"
      - name: Build snapcraft
        id: snapcraft
        uses: snapcore/action-build@v1
      - name: Check build result
        if: ${{ env.DEBUG }}
        run: |
          ls -al ${{ steps.snapcraft.outputs.snap }}
      - name: Upload artifact
        if: ${{ env.UPLOAD_ARTIFACT == 'yes' }}
        uses: actions/upload-artifact@v2
        with:
          name: loopchain_snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - name: Publish to snap store
        if: ${{ success() && env.RELEASE_TAG != '' }}
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: ${{ format('edge/{0}', env.RELEASE_TAG) }}
